
Comic.create(title: "Comic_1", img_url: "http://fpoimg.com/600x700?text=Comic_1")
Comic.create(title: "Comic_2", img_url: "http://fpoimg.com/600x700?text=Comic_2")
Comic.create(title: "Comic_3", img_url: "http://fpoimg.com/600x700?text=Comic_3")
Comic.create(title: "Comic_4", img_url: "http://fpoimg.com/600x700?text=Comic_4")
Comic.create(title: "Comic_5", img_url: "http://fpoimg.com/600x700?text=Comic_5")


Post.create(title: "Bacon", user_id: 1, banner_url: "http://fpoimg.com/800x200", description: "Jowl boudin salami, brisket sirloin ribeye flank. Chuck tongue sirloin, shoulder jerky corned beef short loin. Kevin salami cupim chicken ham hock sirloin short ribs pork flank ground round landjaeger pig. Pastrami leberkas t-bone landjaeger frankfurter sausage.", body: "Bacon ipsum dolor amet fatback ham hock prosciutto drumstick venison salami shoulder brisket swine. Bresaola andouille jerky leberkas cow fatback. Ball tip andouille jerky shank fatback, jowl corned beef tail brisket tongue short loin boudin salami. Salami shank brisket ribeye ball tip pancetta shoulder bresaola meatloaf fatback hamburger. Porchetta sirloin shank pancetta ground round, t-bone fatback pork. Kielbasa filet mignon pork chop tail.

Jowl boudin salami, brisket sirloin ribeye flank. Chuck tongue sirloin, shoulder jerky corned beef short loin. Kevin salami cupim chicken ham hock sirloin short ribs pork flank ground round landjaeger pig. Pastrami leberkas t-bone landjaeger frankfurter sausage.

Cow pork loin shankle, frankfurter t-bone rump capicola kielbasa ball tip beef. Capicola ham strip steak cupim, short ribs beef ribs bresaola turducken turkey tri-tip pork belly porchetta flank chuck ball tip. Jerky capicola short loin, drumstick fatback andouille ham strip steak picanha meatball. Filet mignon ribeye frankfurter sausage tri-tip meatball shankle boudin pancetta tongue bresaola pork belly picanha. Brisket biltong meatball cow rump pork chop. Leberkas tri-tip sirloin flank jerky shank, pork belly sausage ground round filet mignon drumstick. Spare ribs fatback pancetta meatloaf, chuck bresaola flank pork belly ground round shank.

Flank chicken chuck tail porchetta short loin. Ham doner tenderloin cupim, biltong tail corned beef tongue chuck jowl prosciutto pork chop porchetta turducken capicola. Chicken bacon chuck, fatback ham pancetta shoulder landjaeger. Strip steak ham bacon meatloaf.

Filet mignon pastrami pork belly sirloin. Chuck kevin strip steak kielbasa pork chop. Filet mignon ribeye cupim alcatra biltong leberkas drumstick. Filet mignon prosciutto beef ham, strip steak leberkas cow.")

Post.create(title: 'Gangster', user_id: 2, banner_url: "http://fpoimg.com/800x200", description: 'Dang ipsum dolor sit black, funky fresh adipiscing elit. Nullam sapien velizzle, funky fresh volutpizzle, suscipit quis, break yo neck, yall brizzle, crazy. Pellentesque eget tortor. Fizzle erizzle. Da bomb izzle dolizzle you son of a bizzle turpis tempizzle yippiyo. Maurizzle pellentesque nibh hizzle turpizzle. Shut the shizzle up izzle tortor. Pellentesque check it out nisi. In for sure habitasse platea dictumst. Dawg dapibus. Curabitur fo shizzle mah nizzle fo rizzle, mah home g-dizzle urna, pretizzle eu, mattizzle izzle, dizzle cool, nunc. I saw beyonces tizzles and my pizzle went crizzle suscipizzle. Integizzle semper pizzle sed its fo rizzle.', body: "Dang ipsum dolor sit black, funky fresh adipiscing elit. Nullam sapien velizzle, funky fresh volutpizzle, suscipit quis, break yo neck, yall brizzle, crazy. Pellentesque eget tortor. Fizzle erizzle. Da bomb izzle dolizzle you son of a bizzle turpis tempizzle yippiyo. Maurizzle pellentesque nibh hizzle turpizzle. Shut the shizzle up izzle tortor. Pellentesque check it out nisi. In for sure habitasse platea dictumst. Dawg dapibus. Curabitur fo shizzle mah nizzle fo rizzle, mah home g-dizzle urna, pretizzle eu, mattizzle izzle, dizzle cool, nunc. I saw beyonces tizzles and my pizzle went crizzle suscipizzle. Integizzle semper pizzle sed its fo rizzle.

Praesent non mi dang maurizzle mah nizzle hizzle. Aliquizzle lacinia viverra lectizzle. Da bomb id gizzle et phat own yo' ghetto. Aliquizzle lobortis, brizzle brizzle dapibizzle dope, nulla for sure bibendizzle metus, izzle ass augue dui in check it out. Vivamizzle gravida lacizzle fo shizzle fo shizzle my nizzle. Mofo arcu sure, fermentum shizznit amizzle, dope izzle, mofo izzle, the bizzle. Its fo rizzle own yo' laorizzle daahng dawg. Cool fizzle dizzle, hendrerizzle izzle, izzle, malesuada a, bizzle. Morbi aliquam placerizzle dawg. Fo dawg erizzle crackalackin erizzle. Fo metizzle sem, egestas i saw beyonces tizzles and my pizzle went crizzle, accumsizzle quizzle, elementizzle crackalackin, neque. Rizzle iaculizzle nunc a orci tincidunt crunk. Fusce sagittis, sure fizzle sollicitudizzle away, brizzle break yo neck, yall fo shizzle mah nizzle fo rizzle, mah home g-dizzle erat, vitae break yo neck, yall augue crazy vitae arcu. Etizzle that's the shizzle lacizzle. Nunc dizzle uhuh ... yih!. Duis i'm in the shizzle turpizzle. Vestibulizzle pimpin' crunk. Boofron turpizzle boofron, phat fo shizzle, tempizzle izzle, yippiyo in, pede. Nunc mah nizzle. Nulla shizznit eros, pimpin' tellivizzle , ultricies at, tincidunt non, augue.

Praesent nizzle my shizz crackalackin leo bibendizzle molestie. Bow wow wow own yo' tortizzle stuff doggy. Yippiyo malesuada fo shizzle magna. Morbi hizzle, stuff tellivizzle dang egestizzle, dawg uhuh ... yih! break yo neck, yall ligula, ac pimpin' justo ma nizzle quizzle augue. Da bomb id ass sit fo shizzle mah nizzle fo rizzle, mah home g-dizzle erizzle uhuh ... yih! yo. Yo mamma shiz boom shackalack ut fo. In rhoncizzle dizzle leo. Lorizzle break it down own yo' sizzle amizzle, consectetizzle adipiscing elit. Phasellus nisi ass, phat sizzle , facilisizzle sed, tristique , libero. sempizzle faucibizzle diam. For sure nizzle shiz. Nunc da bomb risizzle a crackalackin shut the shizzle up egestizzle. Bizzle condimentizzle fizzle laoreet black. Aenizzle brizzle, the bizzle quizzle varizzle fo shizzle my nizzle, lectizzle diam commodo its fo rizzle, break yo neck, yall sizzle erizzle nisl quizzle nisi. Vivamus pizzle quizzle, aliquizzle sizzle amet, ornare nizzle, pulvinizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, felis.

Uhuh ... yih! ut dolor. Fusce magna ligula, dignissim sit amizzle, fringilla egizzle, sollicitudizzle da bomb, dope. Sizzle a nisi. Dizzle nizzle neque black risus. Bizzle da bomb. Cras aliquizzle gizzle turpis. Suspendisse dizzle ultrices black. Gangsta fo shizzle my nizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, pharetra nizzle, posuere break it down, dapibus fo shizzle mah nizzle fo rizzle, mah home g-dizzle, augue. Izzle izzle pot. Aenizzle fo shizzle my nizzle lectus pimpin' amizzle go to hizzle. Fusce dapibus felizzle owned arcu. Ma nizzle yippiyo sizzle sizzle amizzle, bizzle rizzle dizzle. Nizzle massa purus, eleifend laoreet, shiz id, consequat that's the shizzle, elizzle. Sure ass fo shizzle nunc.

Crackalackin ultrices, boom shackalack et blandit break yo neck, yall, nibh quizzle izzle dizzle, sizzle owned hizzle justo boofron my shizz. Maecenas yippiyo, mah nizzle elementizzle owned fermentizzle, sheezy maurizzle daahng dawg , ut vehicula nisl velizzle sizzle maurizzle. Yippiyo nulla ass, imperdiet dizzle, malesuada volutpat, check out this fizzle, pede. Vivamus urna. Curabitur placerat, phat quis cursus blandizzle, i'm in the shizzle augue shiz dui, shizzle my nizzle crocodizzle bibendizzle fo shizzle ipsizzle non erizzle. Phat crazy. Nam sizzle ghetto da bomb sem ornare hizzle. Integizzle cursizzle, turpis shut the shizzle up auctizzle check out this, fo shizzle purizzle semper sem, sizzle dang laorizzle mi felizzle fizzle massa. Boofron id orci. In hac habitasse shut the shizzle up dictumst. Maecenas we gonna chung owned, faucibus shiz, sempizzle shit, congue izzle, quizzle. Aliquam tellizzle sem, crunk check it out, ultricizzle my shizz, euismizzle nizzle, leo. Duis dawg magna check it out quizzle pulvinizzle away. Lorizzle i'm in the shizzle dolor sit that's the shizzle, consectetuer adipiscing funky fresh.

Morbi shut the shizzle up. Break it down potenti. Maecenizzle get down get down. Etizzle stuff pizzle, gangsta quizzle, stuff ut, scelerisque gangsta, pizzle. Morbi neque. Stuff sure. Go to hizzle nonummy, bizzle vitae shizzlin dizzle crunk, libero mi da bomb things, gangster laoreet gangsta enizzle augue. Curabitizzle mammasay mammasa mamma oo sa nibh vizzle dawg. Fusce bibendum dolizzle nizzle libero. Go to hizzle crackalackin, metizzle vizzle check it out lacinia, erizzle pharetra tortizzle, eu luctizzle boom shackalack est daahng dawg pot.")

Post.create(title: "Hipster", user_id: 1, banner_url: "http://fpoimg.com/800x200", description: "Carles VHS roof party art party, next level forage mixtape. Pop-up distillery Vice, occupy hashtag trust fund Godard selfies gluten-free. Health goth you probably haven't heard of them banh mi leggings, Intelligentsia organic Bushwick tousled Blue Bottle meggings pickled hella twee. Listicle Intelligentsia retro lumbersexual, 8-bit yr irony narwhal Banksy kitsch sustainable banjo Shoreditch. Cred cornhole skateboard, Vice Odd Future Williamsburg wolf street art banh mi semiotics before they sold out. Biodiesel stumptown Williamsburg, hoodie slow-carb meggings forage wayfarers. Lomo mumblecore readymade slow-carb, gluten-free post-ironic pour-over tote bag 8-bit.", body: "Carles VHS roof party art party, next level forage mixtape. Pop-up distillery Vice, occupy hashtag trust fund Godard selfies gluten-free. Health goth you probably haven't heard of them banh mi leggings, Intelligentsia organic Bushwick tousled Blue Bottle meggings pickled hella twee. Listicle Intelligentsia retro lumbersexual, 8-bit yr irony narwhal Banksy kitsch sustainable banjo Shoreditch. Cred cornhole skateboard, Vice Odd Future Williamsburg wolf street art banh mi semiotics before they sold out. Biodiesel stumptown Williamsburg, hoodie slow-carb meggings forage wayfarers. Lomo mumblecore readymade slow-carb, gluten-free post-ironic pour-over tote bag 8-bit.

Yr literally kogi, ethical ennui dreamcatcher cold-pressed umami Neutra scenester occupy Carles 8-bit keytar XOXO. YOLO food truck typewriter, kale chips locavore messenger bag mustache chia lomo direct trade. Fap plaid Schlitz, brunch butcher salvia Cosby sweater sriracha tousled Helvetica fixie narwhal fanny pack. Mixtape bitters chillwave, Pinterest vegan bespoke pop-up sartorial cardigan. Art party McSweeney's bitters, shabby chic lo-fi Vice pug. Sartorial Godard Tonx polaroid, cray paleo trust fund fixie four loko Cosby sweater tote bag. Synth vegan leggings fingerstache mlkshk.

Banjo freegan Pinterest pickled literally Etsy. Deep v Austin pop-up Schlitz, keytar synth Tonx biodiesel master cleanse wolf Neutra twee drinking vinegar iPhone. Pop-up banh mi Neutra meh, Thundercats bespoke craft beer roof party mumblecore American Apparel Cosby sweater Carles. Schlitz yr Brooklyn fap Austin, lo-fi shabby chic Godard dreamcatcher. Kickstarter tattooed bespoke, meh kale chips mustache authentic tilde wayfarers Intelligentsia kogi Thundercats tote bag. 90's hashtag readymade actually. Actually Kickstarter viral selfies Odd Future, artisan Pitchfork Brooklyn irony heirloom stumptown direct trade.

High Life wolf tote bag Thundercats trust fund. Artisan mlkshk bicycle rights, drinking vinegar food truck bespoke yr. Yr flexitarian cardigan, Odd Future brunch photo booth Intelligentsia normcore master cleanse. Tattooed semiotics try-hard, umami actually literally meh cardigan +1 twee kale chips. Letterpress sriracha quinoa bespoke synth Vice gluten-free, taxidermy lomo. Ethical Pinterest you probably haven't heard of them chia, banh mi bicycle rights tilde lumbersexual. Tofu raw denim meggings, gentrify occupy fap fanny pack keffiyeh butcher literally Blue Bottle Pitchfork pour-over normcore.")

Post.create(title: "Samuel L. Jackson", user_id: 2, banner_url: "http://fpoimg.com/800x200", description: "The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee.", body: "The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee.

Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass.

Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing.

Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb.

My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?")

Post.create(title: 'Web 2.0', user_id: 1, banner_url: "http://fpoimg.com/800x200", description: "Webtwo ipsum dolor sit amet, eskobo chumby doostang bebo. Plickers prezi chumby napster kazaa empressr ifttt, kazaa geni cotweet wufoo meevee. Eskobo glogster napster kosmix jabber weebly dogster zynga meevee chartly dogster zoodles, diigo chegg tumblr divvyshot zinch glogster gooru blippy doostang lala. Eskobo stypi kno mog rovio joukuu blekko zoodles ngmoco zappos shopify, skype babblely xobni meevee mzinga udemy zappos groupon elgg. Zooomr gsnap unigo omgpop xobni greplin, zimbra nuvvo zoodles jumo heekya woopra, hipmunk woopra waze cloudera. Kiko jaiku koofers dropio chegg zynga gsnap balihoo divvyshot rovio, kazaa jajah kno unigo grockit voxy napster. ", body: "Webtwo ipsum dolor sit amet, eskobo chumby doostang bebo. Plickers prezi chumby napster kazaa empressr ifttt, kazaa geni cotweet wufoo meevee. Eskobo glogster napster kosmix jabber weebly dogster zynga meevee chartly dogster zoodles, diigo chegg tumblr divvyshot zinch glogster gooru blippy doostang lala. Eskobo stypi kno mog rovio joukuu blekko zoodles ngmoco zappos shopify, skype babblely xobni meevee mzinga udemy zappos groupon elgg. Zooomr gsnap unigo omgpop xobni greplin, zimbra nuvvo zoodles jumo heekya woopra, hipmunk woopra waze cloudera. Kiko jaiku koofers dropio chegg zynga gsnap balihoo divvyshot rovio, kazaa jajah kno unigo grockit voxy napster.

Kaboodle blyve hulu boxbe grockit disqus jajah wakoopa mobly voki empressr, oooj skype eduvant trulia lanyrd chegg wufoo octopart bebo, yoono chumby hulu jabber tivo bubbli plickers oovoo cotweet. Jabber mozy loopt whrrl diigo spotify grockit dropio odeo, skype wufoo palantir blippy yoono zlio. Plugg kippt unigo groupon cloudera eduvant rovio zynga jumo lala shopify woopra chartly sifteo, cloudera kazaa voki twitter nuvvo babblely vuvox woopra blippy chegg zoho klout. Spock ideeli cotweet joost mobly jajah kazaa boxbe gooru zappos, udemy balihoo mozy etsy kippt orkut ifttt weebly.

Ifttt airbnb dogster convore airbnb imeem jibjab wesabe imvu octopart, vuvox napster spock vimeo dogster blekko spock xobni voxy, plugg kosmix sclipo kaboodle sococo eduvant bebo grockit. Kno shopify plickers skype kosmix scribd zoodles vimeo, kippt mog woopra mog meebo sifteo. Foodzie lanyrd kippt jabber napster palantir elgg zanga twones zooomr wakoopa, mzinga bitly elgg zillow zanga disqus octopart rovio eskobo chegg, yuntaa disqus zooomr ning eskobo nuvvo lanyrd movity hulu. Mobly zappos quora kaboodle unigo hojoki vuvox, fleck cotweet blyve appjet blippy, bebo appjet dropio zooomr spotify.

Oovoo dopplr tivo chegg greplin omgpop chumby zoodles, gooru skype dropio tivo jabber orkut ideeli, waze zinch unigo yuntaa plaxo gsnap. Spotify wakoopa chartly chegg diigo waze, appjet ideeli klout spotify ideeli orkut, babblely gsnap convore kno. Rovio wesabe blekko yammer yuntaa mog, ebay knewton dogster xobni sifteo, kosmix blippy wakoopa joukuu. Klout stypi mzinga plickers oovoo mog meevee orkut, voki mobly chartly boxbe chartly bitly, chegg jabber heekya zooomr zappos voki. Plaxo knewton chumby kno divvyshot bebo cotweet heekya ifttt, zoodles plaxo revver twones joost prezi cuil.

Blippy loopt shopify oooj plaxo zinch joyent yuntaa vimeo octopart twitter, trulia vuvox sclipo lanyrd airbnb kiko qeyno vimeo bitly, elgg spock stypi trulia bitly kosmix jibjab prezi plugg. Loopt mzinga woopra lijit yuntaa blyve trulia rovio loopt foodzie movity nuvvo glogster hojoki eduvant, octopart voxy oooj cotweet convore handango loopt zlio waze blyve jaiku napster gsnap. Kiko xobni sococo zooomr spock vuvox sococo zappos octopart, kaboodle flickr koofers jibjab heekya stypi greplin, dropio whrrl imeem scribd zooomr jabber jiglu. Orkut wakoopa dopplr twitter zoho, appjet heroku blippy")
